services:
    ddx.base:
        class: Ddx\Dr\ReaderBundle\Service\DdxDrBaseService
        arguments: [@service_container]
        
    ddx.kraken:
        class: Ddx\Dr\ReaderBundle\Service\KrakenMarketService
        arguments: [@service_container]
