services:
    ddx.kraken:
        class: Ddx\Dr\ReaderBundle\Service\KrakenMarketService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            tradeService: "@ddx.trade"
            tradingPairService: "@ddx.tradingpair"
            parameters : ['%kraken%']

    ddx.helper:
        class: Ddx\Dr\ReaderBundle\Service\BaseHelper
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            tradeService: "@ddx.trade"
            tradingPairService: "@ddx.tradingpair"
            krakenMarketService: "@ddx.kraken"