services:
    ddx.tradingpair:
        class: Ddx\Dr\MarketBundle\Service\TradingPairService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    ddx.trade:
        class: Ddx\Dr\MarketBundle\Service\TradeService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            