services:
    ddx.tradingpair:
        class: Ddx\Dr\MarketBundle\Service\TradingPairService
        arguments: [@service_container]
        
    ddx.trade:
        class: Ddx\Dr\MarketBundle\Service\TradeService
        arguments: [@service_container]
