ddxdr_kraken_history:
    path:     /kraken/history
    methods: [ get ]
    defaults: { _controller: DdxDrWebBundle:Index:krakenHistory }
    
    
ddxdr_kraken_ohlc:
    path:     /kraken/ohlc
    methods: [ get ]
    defaults: { _controller: DdxDrWebBundle:Index:krakenOHLC }
